name: Build Handout
on: [push]
# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
          working_directory: tex/handout/
          root_file: Handout_OS2024_Mocsy.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tex/handout/Handout_OS2024_Mocsy.pdf
      - name: upload as latest release
        run: |
          cd ${{github.workspace}}
          gh release upload v0.9.0 tex/handout/Handout_OS2024_Mocsy.pdf
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
